Require Import SkillAchievability.
Print Assumptions refutation_sound.
Print Assumptions tolerance_sound.
Print Assumptions cap_monotone.
Print Assumptions FlightInstance.flight_refuted.
Print Assumptions FlightInstance.booking_reachable.
Print Assumptions refutation_sound_rel.
Print Assumptions refutation_sound_fun_is_rel.
Print Assumptions SymbolicInstance.symbolic_refutation_sound.
