(* Axiom-freeness harness for the severity/k-resilience development.
   Every result must print "Closed under the global context". *)
Require Import Severity.

Print Assumptions TC_sound.
Print Assumptions TC_complete.
Print Assumptions TC_exact.
Print Assumptions tolerance_downward_closed.
Print Assumptions severity_disjoint.
Print Assumptions severity_exhaustive.
Print Assumptions catastrophe_implies_untypable.
Print Assumptions untypable_implies_catastrophe.
Print Assumptions reach_monotone_in_ctx.
Print Assumptions tolerance_antitone_in_ctx.
Print Assumptions repair_narrow_sound.
Print Assumptions Gbad_is_0_tolerant.
Print Assumptions Gbad_not_1_tolerant.
Print Assumptions Ggood_is_k_tolerant.
Print Assumptions Ggood_by_narrowing.
Print Assumptions TC_seq.
Print Assumptions TC_seq_interface.
Print Assumptions ends_budget_le.
Print Assumptions reach_mono_budget.
Print Assumptions catastrophic_upward.
Print Assumptions futile_downward.
Print Assumptions benign_no_regress.
Print Assumptions benign_step_up.
Print Assumptions benign_step_down.
Print Assumptions severity_monotone_in_budget.
Print Assumptions tolerance_degree_is_a_threshold.
Print Assumptions severity_classes_are_separated.
Print Assumptions assured_reach.
Print Assumptions assured_downward.
Print Assumptions robust_benign.
Print Assumptions principal_characterises.
Print Assumptions principal_unique.
Print Assumptions principal_exists.
Print Assumptions reach_cone.
Print Assumptions safeT_cone.
Print Assumptions interface_projection.
