Require Import Bridge.
Print Assumptions bridge_step.
Print Assumptions bridge_run.
Print Assumptions budget_distributes.
Print Assumptions total_eq_sum_percost.
Print Assumptions progress.
Print Assumptions every_label_steps.
Print Assumptions Ggood_inhabited.
Print Assumptions Gbad_inhabited.
Print Assumptions Gbad_bridge_nonvacuous.
