Require Import Abort.
Print Assumptions E2_cap_enabled.
Print Assumptions E2_no_halted.
Print Assumptions E2_idle_aborted.
Print Assumptions E2_inert_abort.
Print Assumptions E2_validates.
Print Assumptions Gbad3_not_1_tolerant.
Print Assumptions SafePath_E2_safe.
Print Assumptions Gguarded_is_k_tolerant.
Print Assumptions Gguarded_inhabited.
Print Assumptions Gguarded_bridge_nonvacuous.
Print Assumptions SafePath_safe_anywhere.
Print Assumptions congruence_is_not_degenerate.
Print Assumptions E4_validates.
Print Assumptions E4_no_halted.
Print Assumptions E4_not_idle.
Print Assumptions Gguarded_not_1_tolerant_in_E4.
Print Assumptions reordered_not_tolerant_in_E4.
