Require Import Bridge.
Print Assumptions bridge_step.
Print Assumptions bridge_run.
Print Assumptions budget_distributes.
Print Assumptions total_eq_sum_percost.
Print Assumptions progress.
Print Assumptions every_label_steps.
Print Assumptions Ggood_inhabited.
Print Assumptions Gbad_inhabited.
Print Assumptions Gbad_bridge_nonvacuous.
Print Assumptions markers_are_met.
Print Assumptions marker_reached_is_not_futile.
Print Assumptions Ggoal_is_k_tolerant.
Print Assumptions Ggoal_inhabited.
Print Assumptions Ggoal_marker_met.
Print Assumptions ctypes_comm_labels.
Print Assumptions narrowing_breaks_conformance.
Print Assumptions narrowing_asymmetry.
Print Assumptions Gloss_safe.
Print Assumptions benign_is_not_robust.
Print Assumptions hrun_split.
Print Assumptions bridge_every_configuration.
Print Assumptions MBad_takes_the_wrong_branch.
Print Assumptions SafePath_assures_Phi0.
Print Assumptions Ggood_is_robust.
Print Assumptions cone_is_not_degenerate.
Print Assumptions ctypes_ext.
Print Assumptions canon_other.
Print Assumptions label_determines.
Print Assumptions canon_conforms.
Print Assumptions two_role_bridge_nonvacuous.
