#!/usr/bin/env python3
"""Dump the Coq statement of every result the paper cites.

`check_paper_citations.py` proves the citations resolve and are audited.
This one answers the next question a referee asks: does each result *say
what the paper says it says*?  It runs `Check` on every cited name and
writes the elaborated statements to proof/STATEMENTS.md, grouped by file.

Needs coqc on PATH and the development already built (`make` in proof/).
"""
import ast
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WIP = ROOT / "paper" / "WIP"
PROOF = WIP / "proof"
OUT = PROOF / "STATEMENTS.md"

DEF = (r"(Theorem|Lemma|Corollary|Definition|Fixpoint|Inductive|CoInductive|"
       r"Record|Proposition)")
CONSTRUCTOR = r"^\s*\|\s*{name}\s*:"      # a constructor of an inductive
ORDER = ["Severity", "Bridge", "Regular", "Mu", "Repairs", "Abort",
         "Interleave", "Kernel", "DeviationLayer"]


def cited() -> list[str]:
    tex = (WIP / "main.tex").read_text(encoding="utf-8")
    names = {n.replace("\\_", "_") for n in re.findall(r"\\coqok\{([^}]*)\}", tex)}
    names.discard("name")
    return sorted(names)


def locate(names: list[str]) -> dict[str, list[str]]:
    by_file: dict[str, list[str]] = {}
    seen: set[str] = set()
    for p in sorted(PROOF.glob("*.v")):
        if p.name.startswith("check_") or p.stem == "extract":
            continue
        src = p.read_text(encoding="utf-8")
        for n in names:
            if n in seen:
                continue
            if (re.search(rf"^\s*{DEF}\s+{re.escape(n)}\b", src, re.M)
                    or re.search(CONSTRUCTOR.format(name=re.escape(n)), src, re.M)):
                by_file.setdefault(p.stem, []).append(n)
                seen.add(n)
    missing = [n for n in names if n not in seen]
    if missing:
        print(f"warning: no definition found for {missing}", file=sys.stderr)
    return by_file


def main() -> int:
    names = cited()
    by_file = locate(names)
    files = [f for f in ORDER if f in by_file] + sorted(set(by_file) - set(ORDER))
    total = sum(len(by_file[f]) for f in files)
    parts = [
        f"# What the paper cites, and what Coq actually says ({total} results)",
        "",
        "Every `\\coqok{...}` citation in `../main.tex`, with the statement Coq",
        "elaborates for it. Generated by `scripts/dump_statements.py`; regenerate",
        "after changing either the paper or the development.",
        "",
        "`scripts/check_paper_citations.py` (run by `tests/test_proof.py`) checks that",
        "every citation is defined and covered by a `Print Assumptions` harness. This",
        "file is so a reader can check that each one *says what the paper says it says*",
        "without opening the sources.",
        "",
    ]
    with tempfile.TemporaryDirectory() as td:
        for f in files:
            ns = sorted(by_file[f])
            probe = Path(td) / f"stmt_{f}.v"
            probe.write_text(f"Require Import {f}.\n"
                             + "".join(f"Check {n}.\n" for n in ns), encoding="utf-8")
            r = subprocess.run(["coqc", "-Q", ".", "", str(probe)],
                               capture_output=True, text=True, cwd=PROOF)
            if r.returncode != 0:
                print(f"coqc failed on {f}:\n{r.stderr}", file=sys.stderr)
                return 1
            parts += [f"## `{f}.v` ({len(ns)} cited)", "", "```coq",
                      r.stdout.rstrip(), "```", ""]
    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"{total} statements written to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
